# Generated by Django 4.1.1 on 2022-09-26 20:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_cellphone_user_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_file_path, verbose_name='Imagen'),
        ),
    ]
